from django.db import models
# Create your models here.
class Template(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    structure = models.TextField(max_length=255)

class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)

class Address(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
class Data(models.Model):
    id=models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    gender = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    skype = models.CharField(max_length=255)
    contact_type = models.CharField(max_length=255)
    birthday = models.CharField(max_length=255)
    birthday_location = models.CharField(max_length=255)
    blood_group = models.CharField(max_length=255)
    material_status = models.CharField(max_length=255)
    user_id = models.CharField(max_length=255)
    latitude = models.CharField(max_length=255)
    longtitude = models.CharField(max_length=255)
    contact_id = models.CharField(max_length=255)
    provider_type = models.CharField(max_length=255)
    user_role = models.CharField(max_length=255)
    opt = models.CharField(max_length=255)
    support_need = models.CharField(max_length=255)
