# Generated by Django 3.0.9 on 2020-09-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='structure',
            field=models.TextField(max_length=255),
        ),
    ]
