# Generated by Django 3.0.9 on 2020-11-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200915_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=255)),
                ('contact_type', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=255)),
                ('birthday_location', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('material_status', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longtitude', models.CharField(max_length=255)),
                ('contact_id', models.CharField(max_length=255)),
                ('provider_type', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=255)),
                ('opt', models.CharField(max_length=255)),
                ('support_need', models.CharField(max_length=255)),
            ],
        ),
    ]
